version: '3'

services:

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy
    ports:
      - "8080:8080"
    restart: unless-stopped

  geo-service:
    build:
      context: .
    container_name: geo-service
    ports:
      - "8081:8081"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - proxy