version: '3'

services:
  hugo:
    image: klakegg/hugo:0.101.0-ext-alpine
    container_name: hugo
    entrypoint: hugo
    command: server --bind 0.0.0.0 --port 1313
    volumes:
      - "./hugo:/src"
    ports:
      - "1313:1313"
    networks:
      - mylocal

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy
    ports:
      - "8080:8080"
    networks:
      - mylocal

networks:
  mylocal:
    driver: bridge