services:

  #proxy:
  #  build:
  #    context: ./proxy
  #    dockerfile: Dockerfile
  #  container_name: proxy
  #  ports:
  #    - "8080:8080"
  #  restart: unless-stopped

  geo-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geo-service
    ports:
      - "8080:8080"
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: geo-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  volumes:
    pgdata: